#
# build_info.py - PlatformIO pre-build script.
#
# Writes include/build_info.h with the git revision, a dirty-tree flag and a
# build timestamp, so the firmware can report exactly which tree it came from.
#
# Two things about this are deliberate:
#
#   1. It generates a HEADER rather than appending -D flags to the build.
#      Project-wide defines are part of every translation unit's command line,
#      so changing one - which the git hash does on every single commit - would
#      rebuild the entire project including Codec2. A header is a dependency
#      only of the files that include it, which is exactly one.
#
#   2. It only rewrites the file when the content actually changes. Otherwise
#      the timestamp would differ on every invocation, the header would look
#      newer than its object, and we would be back to rebuilding constantly.
#      This is also why the timestamp is regenerated but compared - a build
#      that changes nothing else does not churn.
#
# The header is gitignored: it is a build artefact, and committing it would
# mean every commit dirties the tree that the next commit then records.
#
import subprocess
import os
from datetime import datetime, timezone

Import("env")  # noqa: F821  (injected by SCons)

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
OUT = os.path.join(PROJECT_DIR, "include", "build_info.h")


def git(*args):
    """Run a git command in the project directory, or return None."""
    try:
        out = subprocess.check_output(
            ["git", *args],
            cwd=PROJECT_DIR,
            stderr=subprocess.DEVNULL,
        )
        return out.decode("utf-8", "replace").strip()
    except Exception:
        # No git, not a repository, or git refused. Not an error - a firmware
        # built from a tarball is still a firmware, it just cannot say which
        # commit it came from.
        return None


in_repo = git("rev-parse", "--is-inside-work-tree") == "true"

if in_repo:
    rev = git("rev-parse", "--short=7", "HEAD") or "unknown"
    # --porcelain lists modified tracked files AND untracked ones. Both count:
    # a build with uncommitted work in the tree is not reproducible from the
    # hash, which is the whole thing the flag exists to warn about.
    status = git("status", "--porcelain")
    dirty = 1 if status else 0
    branch = git("rev-parse", "--abbrev-ref", "HEAD") or "?"
else:
    rev, dirty, branch = "nogit", 0, "?"

stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

content = f"""// Generated by scripts/build_info.py - do not edit, do not commit.
#pragma once

#define BUILD_GIT_REV    "{rev}"
#define BUILD_GIT_DIRTY  {dirty}
#define BUILD_GIT_BRANCH "{branch}"
#define BUILD_TIMESTAMP  "{stamp}"
"""

# Compare everything except the timestamp line, so an otherwise identical
# rebuild does not touch the file and trigger a recompile.
def strip_stamp(text):
    return "\n".join(
        line for line in text.splitlines() if "BUILD_TIMESTAMP" not in line
    )


previous = ""
if os.path.exists(OUT):
    with open(OUT, "r", encoding="utf-8") as f:
        previous = f.read()

if strip_stamp(previous) != strip_stamp(content):
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"build_info: {rev}{'-dirty' if dirty else ''} on {branch}")
else:
    print(f"build_info: {rev}{'-dirty' if dirty else ''} (unchanged)")
