// =============================================================================
// config_v1.h - the v1 persisted layout. FROZEN.
//
// DO NOT EDIT THIS FILE. Not to add a field, not to fix a comment typo in a
// field name, not to reorder anything for alignment.
//
// This struct describes bytes that exist on boards in the field. It is the
// only remaining description of them, and a migration reads those bytes
// through it. Changing it does not change the bytes - it changes how they are
// interpreted, which is the same thing as corrupting them.
//
// To add a field: edit VoiceConfig in configstore.h, bump CONFIG_VERSION, copy
// this file to config_v2.h, and write the migration. See
// docs/07-config-migration.md.
//
// The static_assert below is what actually enforces "frozen". A comment does
// not: somebody will add a field here by accident one day, and the assert is
// what stops that becoming a silent misread of every stored blob.
// =============================================================================
#pragma once

#include <stdint.h>

struct VoiceConfigV1 {
  uint32_t magic;         //  0
  uint16_t version;       //  4  == 1
  uint16_t size;          //  6  == 44
  uint32_t firmware;      //  8

  uint8_t  key[16];       // 12
  uint8_t  keySet;        // 28

  uint8_t  stationId;     // 29
  uint8_t  preset;        // 30
  uint8_t  encryptOnBoot; // 31
  uint8_t  micGainShift;  // 32
  uint8_t  cueTones;      // 33
  uint8_t  logLevel;      // 34  stored as LogLevel + 1; 0 = not set
  uint8_t  pad0[1];       // 35  reserved in v1; becomes presetMode in v2

  uint16_t prerollMs;     // 36
  uint16_t txMaxSeconds;  // 38

  uint32_t crc;           // 40
};                        // 44

static_assert(sizeof(VoiceConfigV1) == 44,
              "the v1 layout is frozen - see the warning at the top of this file");
